---
version: "3"

services:
  joomla5:
    image: joomla:5
    restart: unless-stopped
    environment:
      JOOMLA_DB_HOST: joomla5db
      JOOMLA_DB_PASSWORD: password
    volumes:
      - joomla5:/var/www/html
    ports:
      - "8085:80"
    networks:
      - joomla
  joomla5db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - joomla5db:/var/lib/mysql
    networks:
      - joomla
  joomla5dbadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - "8585:8080"
    environment:
      - PMA_HOST=joomla5db
    networks:
      - joomla

  joomla6:
    image: joomla:6
    restart: unless-stopped
    environment:
      JOOMLA_DB_HOST: joomla6db
      JOOMLA_DB_PASSWORD: password
    volumes:
      - joomla6:/var/www/html
    ports:
      - "8086:80"
    networks:
      - joomla
  joomla6db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - joomla6db:/var/lib/mysql
    networks:
      - joomla
  joomla6dbadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - "8586:8080"
    environment:
      - PMA_HOST=joomla6db
    networks:
      - joomla

networks:
  joomla:

volumes:
  joomla5:
  joomla5db:
  joomla6:
  joomla6db:
...
